### PR TITLE
fix CTE parser

### LINKED ISSUE #1218: Some CTE statement is parse wrongly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
``` sql
with cte as (select 1) select 1 union with cte as (select 1) select * from cte;
with cte as (select 1) (select 1);
with cte as (select 1) (select 1 union select 1);
select * from (with cte as (select 1) select 1 union select 2) qn;
select * from t where 1 > (with cte as (select 2) select * from cte);
( with cte(n) as ( select 1 ) select n+1 from cte union select n+2 from cte) union select 1;
( with cte(n) as ( select 1 ) select n+1 from cte) union select 1;
( with cte(n) as ( select 1 ) (select n+1 from cte)) union select 1;
```

2. What did you expect to see?

The same as MySQL

3. What did you see instead?
Inconsistent with MySQL

4. What version of TiDB SQL Parser are you using?

master

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve? 

Fix #1218
The with clause should be set before setOprStmt, not selectStmt. 
For example:
with cte as (select 1) select 1 union select 2;

The with clause should be added on the SetOprStmt, not the first selectStmt.
See the added tests.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

File: ast/dml.go [hunk 1]
```diff
@@ -1060,7 +1060,8 @@ type SelectStmt struct {
 	// TableHints represents the table level Optimizer Hint for join type
 	TableHints []*TableOptimizerHint
 	// IsInBraces indicates whether it's a stmt in brace.
-	IsInBraces bool
+	IsInBraces       bool
+	WithBeforeBraces bool
```
Comment (xiongjiwei) [inline ast/dml.go:1064]: it will be useful if add a comment for `WithBeforeBraces`

**Review by xiongjiwei — APPROVED** [review]

File: ast/dml.go (hunk 1 above)
Comment (tangenta) [reply ast/dml.go:1066]: Do you mean parentheses `()`? I remember brace means `{}`.

Comment (kennytm) [reply ast/dml.go:1066]: IsInBraces here refer to the `()` too (why do we need to care if `()` exists anyway). Legacy typo 🤷

Comment (wjhuang2016) [reply ast/dml.go:1066]: It's used to distinguish (with xxx select xxx) and with xxx (select xxx)

**Review by xiongjiwei — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
