### PR TITLE
Fix syntax error caused by unexpected hint

### LINKED ISSUE #987: Unexpected optimizer hint causes syntax error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
SELECT id FROM tbl WHERE id = 0 FOR UPDATE /*+ xyz */;
```

2. What did you expect to see?

In MySQL, an unexpected optimizer hint causes a warning, not an error:

```
mysql> SELECT id FROM tbl WHERE id = 0 FOR UPDATE /*+ xyz */;
Empty set, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------+
| Level   | Code | Message                                             |
+---------+------+-----------------------------------------------------+
| Warning | 1064 | Optimizer hint syntax error near 'xyz */' at line 1 |
+---------+------+-----------------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

This causes a syntax error in TiDB.

```
mysql> SELECT id FROM tbl WHERE id = 0 FOR UPDATE /*+ xyz */;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 53 near "/*+ xyz */"
```

4. What version of TiDB SQL Parser are you using?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.4
Edition: Community
Git Commit Hash: c61fc7247e9f6bc773761946d5b5294d3f2699a5
Git Branch: heads/v4.0.4
UTC Build Time: 2020-07-31 03:49:54
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve? 

close #987 

### What is changed and how it works?

Added a look back token to filter out special case `FOR UPDATE` which might mistakenly take the comment after as a optimization hint.

### Check List 

Tests 

 - Unit test

Code changes

N/A

Side effects

 - Increased code complexity
 
Related changes

N/A

### CODE REVIEW

File: lexer.go [hunk 1]
```diff
@@ -376,8 +378,13 @@ func startWithSlash(s *Scanner) (tok int, pos Pos, lit string) {
 		// See https://dev.mysql.com/doc/refman/5.7/en/optimizer-hints.html
 		if _, ok := hintedTokens[s.lastKeyword]; ok {
 			// only recognize optimizers hints directly followed by certain
-			// keywords like SELECT, INSERT, etc.
-			isOptimizerHint = true
+			// keywords like SELECT, INSERT, etc., only a special case "FOR UPDATE" needs to be handled
+			// we will report a warning in order to match MySQL's behavior, but the hint content will be ignored
```
Comment (kennytm) [inline lexer.go:382]: note the MySQL doesn't necessarily warn, e.g. the following produces no warnings (and the hint is ignored too).

```sql
select 1 for update /*+ hash_join() */;
```

but we don't need to replicate this MySQL behavior. the current solution is good enough.

**Review by kennytm — COMMENTED** [review]
LGTM

**Review by lysu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
