### PR TITLE
*: fix static check report

### LINKED ISSUE #714: Staticcheck report
## Staticcheck Report

1. What did you do?

```bash
$ go get honnef.co/go/tools/cmd/staticcheck
$ GO111MODULE=on staticcheck ./...

ast/advisor.go:17:2: should not use dot imports (ST1001)
ast/ast.go:21:2: should not use dot imports (ST1001)
ast/base.go:99:6: type resultSetNode is unused (U1000)
ast/ddl.go:19:2: should not use dot imports (ST1001)
ast/ddl.go:2700:6: should omit comparison to bool constant, can be simplified to !n.Constraint.Enforced (S1002)
ast/ddl.go:2753:3: this value of col is never used (SA4006)
ast/ddl.go:2760:3: this value of constraint is never used (SA4006)
ast/dml.go:19:2: should not use dot imports (ST1001)
ast/dml.go:70:2: field resultSetNode is unused (U1000)
ast/dml.go:177:2: field resultSetNode is unused (U1000)
ast/dml.go:774:2: field resultSetNode is unused (U1000)
ast/dml.go:1065:2: field resultSetNode is unused (U1000)
ast/dml.go:1889:2: field resultSetNode is unused (U1000)
ast/expressions.go:23:2: should not use dot imports (ST1001)
ast/expressions.go:1183:12: this value of ok is never used (SA4006)
ast/functions.go:22:2: should not use dot imports (ST1001)
ast/misc.go:24:2: should not use dot imports (ST1001)
ast/misc_test.go:195:2: this value of pwd is never used (SA4006)
ast/stats.go:18:2: should not use dot imports (ST1001)
auth/auth.go:23:2: should not use dot imports (ST1001)
charset/charset.go:108:2: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (S1008)
digester.go:117:11: should use d.buffer.String() instead of string(d.buffer.Bytes()) (S1030)
digester.go:124:15: should use d.buffer.String() instead of string(d.buffer.Bytes()) (S1030)
digester.go:247:2: redundant return statement (S1023)
digester.go:363:22: func (*tokenDeque).pushBack is unused (U1000)
goyacc/format_yacc.go:486:2: field readBytes is unused (U1000)
lexer_test.go:219:4: string literal contains the Unicode control character U+0005, consider using the '\x05' escape sequence (ST1018)
lexer_test.go:219:4: string literal contains the Unicode control character U+0018, consider using the '\x18' escape sequence (ST1018)
lexer_test.go:219:22: string literal contains the Unicode control character U+0005, consider using the '\x05' escape sequence (ST1018)
lexer_test.go:219:22: string literal contains the Unicode control character U+0018, consider using the '\x18' escape sequence (ST1018)
lexer_test.go:281:12: this value of lit is never used (SA4006)
lexer_test.go:283:2: this value of tok is never used (SA4006)
lexer_test.go:286:12: this value of lit is never used (SA4006)
lexer_test.go:290:12: this value of lit is never used (SA4006)
misc.go:96:2: redundant return statement (S1023)
model/model.go:620:2: only the first constant in this group has an explicit type (SA9004)
model/model_test.go:151:9: should use String() instead of fmt.Sprintf (S1025)
model/model_test.go:318:7: this value of err is never used (SA4006)
mysql/const.go:21:2: should not use dot imports (ST1001)
mysql/errcode.go:19:2: only the first constant in this group has an explicit type (SA9004)
opcode/opcode.go:21:2: should not use dot imports (ST1001)
parser_test.go:170:3: this value of ss is never used (SA4006)
parser_test.go:2869:2: this value of stmt is never used (SA4006)
parser_test.go:2871:2: this value of stmt is never used (SA4006)
parser_test.go:2874:2: this value of stmt is never used (SA4006)
parser_test.go:3296:2: this value of stmt is never used (SA4006)
parser_test.go:4127:2: this value of stmts is never used (SA4006)
test_driver/test_driver_datum.go:59:2: field collation is unused (U1000)
test_driver/test_driver_datum.go:60:2: field decimal is unused (U1000)
test_driver/test_driver_datum.go:61:2: field length is unused (U1000)
test_driver/test_driver_mydecimal.go:226:12: this value of wordsFrac is never used (SA4006)
yy_parser.go:52:2: var specCodePattern is unused (U1000)
yy_parser.go:58:2: var specVersionCodeValue is unused (U1000)
yy_parser.go:300:6: func getInt64FromNUM is unused (U1000)
```

2. What version of TiDB SQL Parser are you using?

7de2c9958237d536b3f8a632474bedc204a66a95

PTAL @Deardrops

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

close #714, one file one fix commit. There are two commits that may be controversial:

1. https://github.com/pingcap/parser/commit/96e95a2166b386eefd23cadb99ee4c106afa8ff6. It should be a bugfix. If it is major or so, we should cherry-pick.
2. https://github.com/pingcap/parser/commit/6a9bcfc8f629f57f98184bb784d59de8346b91d0. Removed uint16 type, refer to the commit description. Since this package is already deprecated, I think it is ok.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

File: model/model_test.go [hunk 1]
```diff
@@ -152,8 +151,7 @@ func (*testModelSuite) TestJobStartTime(c *C) {
 	}
 	t := time.Unix(0, 0)
 	c.Assert(t, Equals, TSConvert2Time(job.StartTS))
-	ret := fmt.Sprintf("%s", job)
-	c.Assert(job.String(), Equals, ret)
+	c.Assert(job.String(), Equals, job.String())
```
Comment (kennytm) [inline model/model_test.go:154]: this test is thus useless, just asserting the pureness of the `String()` implementation. how about just remove it, or change it to the real expected string.

**Review by kennytm — COMMENTED** [review]
rest LGTM

File: model/model_test.go (hunk 1 above)
Comment (xhebox) [reply model/model_test.go]: Done

**Comment by kennytm** [comment]
```diff
model_test.go:154:
    c.Assert(job.String(), Equals, "ID:123, Type:none, State:none, SchemaState:none, SchemaID:0, TableID:0, RowCount:0, ArgLen:0, start time: 1970-01-01 08:00:00 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0")
... obtained string = "ID:123, Type:none, State:none, SchemaState:none, SchemaID:0, TableID:0, RowCount:0, ArgLen:0, start time: 1970-01-01 00:00:00 +0000 UTC, Err:<nil>, ErrCount:0, SnapshotVersion:0"
... expected string = "ID:123, Type:none, State:none, SchemaState:none, SchemaID:0, TableID:0, RowCount:0, ArgLen:0, start time: 1970-01-01 08:00:00 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"
```

the `start time` is timezone dependent 🤔

**Review by tangenta — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
