### PR TITLE
ast: fix the bug of TableSource.Restore()

### LINKED ISSUE #538: TableSource.Restore produces incorrect (unparsable) SQL when both table's 'asName' and index hints are present
## Bug Report

adding single test to `TestTableNameIndexHintsRestore` 
```
                {"t use index for order by (`foo``bar`) ignore key for group by (`baz``1`, `xyz`)", "`t` USE INDEX FOR ORDER BY (`foo``bar`) IGNORE INDEX FOR GROUP BY (`baz``1`, `xyz`)"},
+
+               {"t tt use index for order by (`foo``bar`) ignore key for group by (`baz``1`, `xyz`)", "`t` AS `tt` USE INDEX FOR ORDER BY (`foo``bar`) IGNORE INDEX FOR GROUP BY (`baz``1`, `xyz`)"},
```
produces an error:
```
... obtained string = "SELECT * FROM `t` USE INDEX FOR ORDER BY (`foo``bar`) IGNORE INDEX FOR GROUP BY (`baz``1`, `xyz`) AS `tt`"
... expected string = "SELECT * FROM `t` AS `tt` USE INDEX FOR ORDER BY (`foo``bar`) IGNORE INDEX FOR GROUP BY (`baz``1`, `xyz`)"
```
note that generated SQL has `AS tt` clause at the very end

attempt to feed generated SQL back into parser produces another error:
`value *errors.withStack = line 1 column 100 near "AS `tt"  ("line 1 column 100 near \"AS `tt\" ")`

2. What did you expect to see?
I'd expect that `Restore` method always produces "correct" SQL (the one that could be parsed again)

3. What did you see instead?
incorrect SQL being generated by Restore

4. What version of TiDB SQL Parser are you using?
```
* commit 275a827cf4e3798ca50ae8b5224895f0919e70ed (upstream/master, origin/master, origin/HEAD, master)
| Author: Tanner <xietengjin@pingcap.com>
| Date:   Mon Sep 2 11:07:20 2019 +0800
```

### PR DESCRIPTION
**Pull request by gleonid**
fix #538. `Restore` method generates incorrect SQL when both table's 'asName' and index hints are present

### Check List
Tests 
 - Unit test
   added

Code changes
 - Has exported function/method change
  no
 - Has exported variable/fields change
  no
 - Has interface methods change
  no

Side effects
 - Possible performance regression
  none
 - Increased code complexity
  special case in `TableSource.Restore` created
 - Breaking backward compatibility
  no

Closes #538

### CODE REVIEW

**Comment by ianzapolsky** [comment]
👍

**Comment by ianzapolsky** [comment]
LGTM

**Comment by zz-jason** [comment]
@gleonid Thanks for your contribution! Please follow the [Commit Message and Pull Request Style](https://github.com/pingcap/community/blob/master/commit-message-pr-style.md) guide to reformat the PR title. BTW, you can use the keywords described in the [Closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords) guide to close the related issue when this PR is merged.

**Comment by gleonid** [comment]
> 
> 
> @gleonid Thanks for your contribution! Please follow the [Commit Message and Pull Request Style](https://github.com/pingcap/community/blob/master/commit-message-pr-style.md) guide to reformat the PR title. BTW, you can use the keywords described in the [Closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords) guide to close the related issue when this PR is merged.

done

File: ast/dml.go [hunk 1]
```diff
@@ -187,12 +187,15 @@ type TableName struct {
 }
 
 // Restore implements Node interface.
-func (n *TableName) Restore(ctx *RestoreCtx) error {
+func (n *TableName) restoreName(ctx *RestoreCtx) {
```
Comment (leoppro) [inline ast/dml.go]: why the permission of this file has been changed?

Comment (gleonid) [reply ast/dml.go]: This file, with go source code, currently has "execute" permission set. This PR removes "execute" bit.
it was set by 02812c3c22e70aa0acd643918ac2152418c11e7c commit on Jan 8 12:41:00 2019

that commit (02812c3c22e70aa0acd643918ac2152418c11e7c) set executable flag on may files, including `parser_test.go`.
Later, on  Aug 14 09:47:16 2019 (commit 91c196d9fac2c5b7769b7be6a8e84aa0bc31036c), executable bit was removed from `parser_test.go`

Looks to me like an unintentional change leaked thru by 02812c3c22e70aa0acd643918ac2152418c11e7c.
Does `ast/dml.go` needs to be executable?

Comment (leoppro) [reply ast/dml.go]: ok, "644" is fine.

**Comment by zz-jason** [comment]
Hi @gleonid, the test in the [tidb](https://github.com/pingcap/tidb) repo failed, could you file a PR to fix that:

```
----------------------------------------------------------------------
PANIC: ranger_test.go:80: testRangerSuite.TestTableRange

ranger_test.go:87:
    c.Assert(err, IsNil)
... value *errors.withStack = [planner:1054]Unknown column 'shutdown_priv' in 'field list' ("[planner:1054]Unknown column 'shutdown_priv' in 'field list'")

... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0xC892EA)

/usr/local/go/src/runtime/panic.go:513
  in gopanic
/usr/local/go/src/runtime/panic.go:82
  in panicmem
/usr/local/go/src/runtime/signal_unix.go:390
  in sigpanic
/go/src/github.com/pingcap/tidb/domain/domain.go:550
  in Domain.Close
ranger_test.go:84
  in testRangerSuite.TestTableRange.func1
/usr/local/go/src/runtime/panic.go:397
  in Goexit
/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:107
  in C.stopNow
/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/helpers.go:179
  in C.Assert
ranger_test.go:87
  in testRangerSuite.TestTableRange
/usr/local/go/src/reflect/value.go:308
  in Value.Call
/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:836
  in suiteRunner.forkTest.func1
/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:730
  in suiteRunner.forkCall.func1
/usr/local/go/src/runtime/asm_amd64.s:1333
  in goexit
OOPS: 1 passed, 6 PANICKED
--- FAIL: TestT (0.52s)
FAIL
```

**Comment by gleonid** [comment]
> 
> 
> Hi @gleonid, the test in the [tidb](https://github.com/pingcap/tidb) repo failed, could you file a PR to fix that:
> 
> ```
> ----------------------------------------------------------------------
> PANIC: ranger_test.go:80: testRangerSuite.TestTableRange
> 
> ranger_test.go:87:
>     c.Assert(err, IsNil)
> ... value *errors.withStack = [planner:1054]Unknown column 'shutdown_priv' in 'field list' ("[planner:1054]Unknown column 'shutdown_priv' in 'field list'")
> 
> ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0xC892EA)
> 
> /usr/local/go/src/runtime/panic.go:513
>   in gopanic
> /usr/local/go/src/runtime/panic.go:82
>   in panicmem
> /usr/local/go/src/runtime/signal_unix.go:390
>   in sigpanic
> /go/src/github.com/pingcap/tidb/domain/domain.go:550
>   in Domain.Close
> ranger_test.go:84
>   in testRangerSuite.TestTableRange.func1
> /usr/local/go/src/runtime/panic.go:397
>   in Goexit
> /go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:107
>   in C.stopNow
> /go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/helpers.go:179
>   in C.Assert
> ranger_test.go:87
>   in testRangerSuite.TestTableRange
> /usr/local/go/src/reflect/value.go:308
>   in Value.Call
> /go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:836
>   in suiteRunner.forkTest.func1
> /go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:730
>   in suiteRunner.forkCall.func1
> /usr/local/go/src/runtime/asm_amd64.s:1333
>   in goexit
> OOPS: 1 passed, 6 PANICKED
> --- FAIL: TestT (0.52s)
> FAIL
> ```

from what I can see "nil pointer dereference" has nothing to do my branch/PR

`domain/domain.go`:
```
    547 // Close closes the Domain and release its resource.
    548 func (do *Domain) Close() {
    549         startTime := time.Now()
    550         if do.ddl != nil {
    551                 terror.Log(do.ddl.Stop())
    552         }
```
appears that `do` is nil on line 550

looking at caller `./util/ranger/ranger_test.go`:
```
     80 func (s *testRangerSuite) TestTableRange(c *C) {
     81         defer testleak.AfterTest(c)()
     82         dom, store, err := newDomainStoreWithBootstrap(c)
     83         defer func() {
     84                 dom.Close()
     85                 store.Close()
     86         }()
     87         c.Assert(err, IsNil)
```
`newDomainStoreWithBootstrap` returns nil for `dom` (and `store`) in case of error.

possible fix could be to move `c.Assert(err, IsNil)` (line 87) in front of defer call, like so:
```
```
     80 func (s *testRangerSuite) TestTableRange(c *C) {
     81         defer testleak.AfterTest(c)()
     82         dom, store, err := newDomainStoreWithBootstrap(c)
     +         c.Assert(err, IsNil)
     83         defer func() {
     84                 dom.Close()
     85                 store.Close()
     86         }()
     -         c.Assert(err, IsNil)
```

I am hesitant to creating PR for this fix, as I mentioned above it has nothing to do with my changes

I will take a look at original failer

**Comment by gleonid** [comment]
I am confused now
I just rebased my branch and force pushed
so now "build-integration" (https://circleci.com/gh/pingcap/parser/3815?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) passed
before force push "build-integration" was failing - https://circleci.com/gh/pingcap/parser/3808?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Is it possible that either:
a. github.com:pingcap/tidb.git has changed (since https://circleci.com/gh/pingcap/parser/3808 ran) and failing tests got fixed purely on tidb side?
b. pingcap/tidb has a flaky test
?

In any case, all now tests are green. 

@ zz-jason  can you please re approve ?
